module.exports.Order_Success = "Order sended successfully"
module.exports.Order_Failed = "Unable send order"
module.exports.Order_Delivery_Successfull = "Order Successfully Delivered"
module.exports.Order_Delivery_Failed = "Order Delivery Failed"
module.exports.Price_Inserted = "Price sended successfully"
module.exports.Price_Insert_Failed = "Unable to insert price try again..."
module.exports.Courier_Assigned_Successful = "Courer assigned successfull"
module.exports.Courier_Assigned_Failed = "Courer assigned failed"
module.exports.SafePayment_Successful = "Safe payment done successfully"
module.exports.Photo_Verified_Successful = "Photo Verified Successfully"
module.exports.Photo_Verified_Failed = "Photo Verification Failed"
module.exports.SafePayment_Faild = "Safe payment failed"
module.exports.Data_Found = "Data Found"
module.exports.Data_Not_Found = "Data Not Found"
module.exports.Order_Accepted = "Order Accepted Successfully"
module.exports.Order_Accepted_Failed = "Order Accepted Failed"
module.exports.Data_Insert_Success = "Data Insert Successful"
module.exports.Data_Insert_Failed = "Unable To Insert Data"
module.exports.Order_Request_Success = "Order Place Successful"
module.exports.Order_Request_Failed = "Order Request Failed"
module.exports.Deployed_Successful = "Product Deployed Successful"
module.exports.Deployed_Failed = "Unable To Deployed "


