module.exports.Order_Success = "Order sended successfully"
module.exports.Order_Failed = "Unable send order"
module.exports.Price_Inserted = "Price sended successfully"
module.exports.Price_Insert_Failed = "Unable to insert price try again..."
module.exports.Data_Found = "Data Found"
module.exports.Data_Not_Found = "Data Not Found"
module.exports.Order_Accepted = "Order Accepted Successfully"
module.exports.Order_Accepted_Failed = "Order Accepted Failed"
module.exports.Data_Insert_Success = "Data Insert Successful"
module.exports.Data_Insert_Failed = "Unable To Insert Data"
module.exports.Order_Request_Success = "Order Place Successful"
module.exports.Order_Request_Failed = "Order Request Failed"
module.exports.Deployed_Successful = "Product Deployed Successful"
module.exports.Deployed_Failed = "Unable To Deployed "


